### ISSUE TITLE
This site can’t provide a secure connection

### ISSUE THREAD

**Issue by lonewolf0708** [h4lfheart/FortnitePorting#23]
Try to access halfheart.dev results in the following error:

This site can’t provide a secure connection

halfheart.dev sent an invalid response.
ERR_SSL_PROTOCOL_ERROR

Which, in return, results in this error:

[07:30:59 INF] [Get] null (0): https://halfheart.dev/fortnite-porting/api/v1/broadcast.json
[07:30:59 ERR] System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at FortnitePorting.Views.LoadingView.OnLoaded(Object sender, RoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by djlorenzouasset** [comment]
this problem is not with the program but is your problem/problem with the API. It works perfectly for me. Have you tried restarting the program?
![img](https://github.com/halfuwu/FortnitePorting/assets/89230676/7b44e52c-ae2b-45f8-ba5a-b96457d198dc)

**Comment by Tevtongermany** [comment]
Works normal for me
![image](https://github.com/halfuwu/FortnitePorting/assets/59411880/046fad77-4b6d-42b2-af8d-fef1267c9939)

![image](https://github.com/halfuwu/FortnitePorting/assets/59411880/70545bdb-c1cf-473b-b1a2-0a4b16556456)
![image](https://github.com/halfuwu/FortnitePorting/assets/59411880/015d603d-3246-41ab-8973-cbbe44d08aeb)

**Comment by lonewolf0708** [comment]
Yes. I get the error with both Live mode and local mode. Restarting modem and PC didn't help. Did for troubleshooting before submitting the issue.

**Comment by h4lfheart** [comment]
would it be possible for you to try a different network? I've heard that seems to help some people

**Comment by lonewolf0708** [comment]
I only have one connection, unfortunately. I have a mobile phone but no hotspot on the plan and halfheart.dev produces the same "This site can't provide a secure connection." error using the browser on the phone.

**Comment by h4lfheart** [comment]
I'm not exactly sure what to do then, it's possible it's an issue on my side but I really don't know what I would do to fix it, the website is just running thru github pages so it's not as if the website was improperly set up

**Comment by lonewolf0708** [comment]
Found a solution. Changed the DNS on my computer via settings to 8.8.8.8 and 8.8.4.4. Now it works as expected so maybe ISP is altering the packets somehow? Maybe put it in troubleshooting tips for those with the same issue.

**Comment by h4lfheart** [comment]
ooh I meant to suggest that before!! glad it worked for ya
