### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by VFXNO** [h4lfheart/FortnitePorting#43]
System.DllNotFoundException: Unable to load DLL 'C:\Users\vfxno.1\Downloads\.data\zlib-ng2.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryPath)
   at ZlibngDotNet.Zlibng..ctor(String libraryPath)
   at CUE4Parse.Compression.ZlibHelper.Initialize(String path)
   at FortnitePorting.ViewModels.CUE4ParseViewModel.InitializeZlib()
   at FortnitePorting.ViewModels.CUE4ParseViewModel.Initialize()
   at FortnitePorting.ViewModels.HomeViewModel.<>c.<<Initialize>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at FortnitePorting.Framework.Services.TaskService.<>c__DisplayClass1_0.<<Run>b__0>d.MoveNext()

**Comment by h4lfheart** [comment]
restart and try again, it's a wifi issue that it's not being downloaded

if that doesn't work move fnporting out of downloads and put it somewhere else where it actually has permissions
